### ISSUE TITLE
Reporte de Diagrama de clase y secuecia

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-8-diagrama-de-clases-secuencia-dinamita#1]
Equipo Dinamita:
Diego Cruz Cruz
Irvin Jiménez Sánchez 
Marco Uriel Rosas Garcia
 
 Diagrama de clase  
[Resporte de Diagrama de Clases y Diagrama Secuencial.pdf](https://github.com/user-attachments/files/18004243/Resporte.de.Diagrama.de.Clases.y.Diagrama.Secuencial.pdf)

Diagrama de Secuencia
[Diagrama de secuencias_Equipo dinamita.pdf](https://github.com/user-attachments/files/18004252/Diagrama.de.secuencias_Equipo.dinamita.pdf)

**Comment by Kevinosorio77** [comment]
De acuerdo ala rubrica contiende todo solo que faltan algunas imagenes en uno calificacion 29

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
